name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  unit-tests:
    name: Run all unit tests (with coverage)
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Create pip requirements
        run: |
          echo "matrix-synapse" > requirements.txt

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Start synapse server
        run: |
          pip install -r requirements.txt
          curl -sL https://gist.githubusercontent.com/ouchadam/e3ad09ec382bd91a66d88ab575ea7c31/raw/run.sh \
            | bash -s -- --no-rate-limit

      - name: Run all unit tests
        run: ./gradlew clean allCodeCoverageReport --no-daemon

      - uses: codecov/codecov-action@v2
        with:
          files: ./build/reports/jacoco/allCodeCoverageReport/allCodeCoverageReport.xml
